public virtual class TriggerHandler {
  public virtual void handleBeforeInsert() {
  }
  public virtual void handleAfterInsert() {
  }
  public virtual void handleBeforeUpdate() {
  }
  public virtual void handleAfterUpdate() {
  }
  public virtual void handleBeforeDelete() {
  }
  public virtual void handleAfterDelete() {
  }
  public virtual void handleAfterUndelete() {
  }
}
/*
public class AccountTriggerHandler extends TriggerHandler { 
public override void handleBeforeInsert() { //Execute our before insert logic }
public override void handleAfterInsert() { //Execute out after insert logic }
public override void handleBeforeUpdate() { //Execute our before insert logic }
public override void handleAfterUpdate() { //Execute out after insert logic }
public override void handleBeforeDelete() { //Execute our before insert logic }
public override void handleAfterDelete() { //Execute out after insert logic }
public override void handleAfterUndelete() { //Execute out after insert logic }

}
*/
